In [75]:
#This creates files from Gorilla

import pandas as pd
import os

In [76]:
in_path = f"{os.getcwd()}\\Data\\Analysis\\Questionnaire_Data\\"
files = os.listdir(in_path)
print(files)

['Long_background.csv', 'Long_TaskAI.csv', 'Long_TaskClean.csv']

In [77]:
out_path = f"{os.getcwd()}\\Data\\Analysis\\"

In [78]:
bg = pd.read_csv(f"{in_path}{files[0]}")
bg.columns

Index(['Event Index', 'UTC Timestamp', 'UTC Date and Time', 'Local Timestamp',
       'Local Timezone', 'Local Date and Time', 'Experiment ID',
       'Experiment Version', 'Tree Node Key', 'Repeat Key', 'Schedule ID',
       'Participant Public ID', 'Participant Private ID',
       'Participant Starting Group', 'Participant Status',
       'Participant Completion Code', 'Participant External Session ID',
       'Participant Device Type', 'Participant Device', 'Participant OS',
       'Participant Browser', 'Participant Monitor Size',
       'Participant Viewport Size', 'Checkpoint', 'Room ID', 'Room Order',
       'Task Name', 'Task Version', 'Page', 'Page ID', 'Page Counter',
       'Question', 'Response Type', 'Key', 'Response', 'Tag', 'OptionOrder',
       'Object Name', 'Object Number', 'Object ID'],
      dtype='object')

In [79]:
clean_columns = ['Participant Private ID', 'Participant Status', 'Task Name', 'Page ID', 'Question','Response','Object ID' ]
bg_clean = bg[clean_columns]
bg_clean

,Participant Private ID,Participant Status,Task Name,Page ID,Question,Response,Object ID
0,12315511.0,complete,Background Questinnaire,NaN,NaN,BEGIN,NaN
1,12315511.0,complete,Background Questinnaire,ukabnm,\n,1,object-3
2,12315511.0,complete,Background Questinnaire,i8g9c4,What is your age,29,object-6
3,12315511.0,complete,Background Questinnaire,i8g9c4,What is your gender,Male,object-7
4,12315511.0,complete,Background Questinnaire,i8g9c4,What is your gender,1,object-7
5,12315511.0,complete,Background Questinnaire,i8g9c4,What is your highest level of education,Master's Degree or equivalent,object-8
6,12315511.0,complete,Background Questinnaire,i8g9c4,What is your highest level of education,4,object-8
7,12315511.0,complete,Background Questinnaire,i8g9c4,Investment experience (years)\n,5,object-9
8,12315511.0,complete,Background Questinnaire,i8g9c4,How often do you engage with stock markets or ...,Weekly,object-10
9,12315511.0,complete,Background Questinnaire,i8g9c4,How often do you engage with stock markets or ...,2,object-10
10,12315511.0,complete,Background Questinnaire,i8g9c4,How often do you engage with AI technologies i...,Weekly,object-18
11,12315511.0,complete,Background Questinnaire,i8g9c4,How often do you engage with AI technologies i...,2,object-18
12,12315511.0,complete,Background Questinnaire,i8g9c4,How would you relate your risk tolerance (1-5),4,object-11
13,12315511.0,complete,Background Questinnaire,i8g9c4,How would you relate your risk tolerance (1-5),4,object-11
14,12315511.0,complete,Background Questinnaire,i8g9c4,How familiar are you with artificial intellige...,4,object-13
15,12315511.0,complete,Background Questinnaire,i8g9c4,How familiar are you with artificial intellige...,4,object-13
16,12315511.0,complete,Background Questinnaire,i8g9c4,How would you rate your knowledge of how Gener...,4,object-14
17,12315511.0,complete,Background Questinnaire,i8g9c4,How would you rate your knowledge of how Gener...,4,object-14
18,12315511.0,complete,Background Questinnaire,i8g9c4,To what extent do you Generative AI systems to...,2,object-15
19,12315511.0,complete,Background Questinnaire,i8g9c4,To what extent do you Generative AI systems to...,2,object-15
20,12315511.0,complete,Background Questinnaire,i8g9c4,How confident are you in your ability to make ...,4,object-17
21,12315511.0,complete,Background Questinnaire,i8g9c4,How confident are you in your ability to make ...,4,object-17
22,12315511.0,complete,Background Questinnaire,NaN,NaN,END,NaN
23,12315870.0,complete,Background Questinnaire,NaN,NaN,BEGIN,NaN
24,12315870.0,complete,Background Questinnaire,ukabnm,\n,1,object-3
25,12315870.0,complete,Background Questinnaire,i8g9c4,What is your age,25,object-6
26,12315870.0,complete,Background Questinnaire,i8g9c4,What is your gender,Female,object-7
27,12315870.0,complete,Background Questinnaire,i8g9c4,What is your gender,2,object-7
28,12315870.0,complete,Background Questinnaire,i8g9c4,What is your highest level of education,Master's Degree or equivalent,object-8
29,12315870.0,complete,Background Questinnaire,i8g9c4,What is your highest level of education,4,object-8
30,12315870.0,complete,Background Questinnaire,i8g9c4,Investment experience (years)\n,3,object-9
31,12315870.0,complete,Background Questinnaire,i8g9c4,How often do you engage with stock markets or ...,Rarely,object-10
32,12315870.0,complete,Background Questinnaire,i8g9c4,How often do you engage with stock markets or ...,4,object-10
33,12315870.0,complete,Background Questinnaire,i8g9c4,How often do you engage with AI technologies i...,Occasionally,object-18
34,12315870.0,complete,Background Questinnaire,i8g9c4,How often do you engage with AI technologies i...,3,object-18
35,12315870.0,complete,Background Questinnaire,i8g9c4,How would you relate your risk tolerance (1-5),4,object-11
36,12315870.0,complete,Background Questinnaire,i8g9c4,How would you relate your risk tolerance (1-5),4,object-11
37,12315870.0,complete,Background Questinnaire,i8g9c4,How familiar are you with artificial intellige...,3,object-13
38,12315870.0,complete,Background Questinnaire,i8g9c4,How familiar are you with artificial intellige...,3,object-13
39,12315870.0,complete,Background Questinnaire,i8g9c4,How would you rate your knowledge of how Gener...,2,object-14
40,12315870.0,complete,Background Questinnaire,i8g9c4,How would you rate your knowledge of how Gener...,2,object-14
41,12315870.0,complete,Background Questinnaire,i8g9c4,To what extent do you Generative AI systems to...,2,object-15
42,12315870.0,complete,Background Questinnaire,i8g9c4,To what extent do you Generative AI systems to...,2,object-15
43,12315870.0,complete,Background Questinnaire,i8g9c4,How confident are you in your ability to make ...,3,object-17
44,12315870.0,complete,Background Questinnaire,i8g9c4,How confident are you in your ability to make ...,3,object-17
45,12315870.0,complete,Background Questinnaire,NaN,NaN,END,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
# Pivot table
bg_compiled = bg_clean.pivot_table(
    index='Participant Private ID',  # rows
    columns='Question',              # columns
    values='Response',               # values to fill
    aggfunc='last'  
).reset_index()

In [81]:
bg_compiled.head()
bg_compiled.to_csv(f"{out_path}Participant_Background.csv")

## Ai task

In [82]:
ai_task = pd.read_csv(f"{in_path}{files[1]}")
ai_task.columns

Index(['Event Index', 'UTC Timestamp', 'UTC Date and Time', 'Local Timestamp',
       'Local Timezone', 'Local Date and Time', 'Experiment ID',
       'Experiment Version', 'Tree Node Key', 'Repeat Key', 'Schedule ID',
       'Participant Public ID', 'Participant Private ID',
       'Participant Starting Group', 'Participant Status',
       'Participant Completion Code', 'Participant External Session ID',
       'Participant Device Type', 'Participant Device', 'Participant OS',
       'Participant Browser', 'Participant Monitor Size',
       'Participant Viewport Size', 'Checkpoint', 'Room ID', 'Room Order',
       'Task Name', 'Task Version', 'Unnamed: 28', 'Page', 'Page ID',
       'Page Counter', 'Question', 'Response Type', 'Key', 'Response', 'Tag',
       'OptionOrder', 'Object Name', 'Object Number', 'Object ID',
       'Manipulation: '],
      dtype='object')

In [83]:
ai_task_columns = ['Participant Private ID','Page', 'Question', 'Response', 'Response Type']
ai_task_clean = ai_task[ai_task_columns]
ai_task_clean

,Participant Private ID,Page,Question,Response,Response Type
0,12315511.0,NaN,NaN,BEGIN,info
1,12315511.0,Page 22,NaN,100,info
2,12315511.0,Page 133,NaN,100,info
3,12315511.0,Page 28,NaN,100,info
4,12315511.0,Page 36,NaN,100,info
...,...,...,...,...,...
2400,12315870.0,Page 150,Do you believe the analysis in the visualizati...,3,response
2401,12315870.0,Page 150,How clear do you think the visualization is (1-5),3,response
2402,12315870.0,Page 150,How clear do you think the visualization is (1-5),3,response
2403,12315870.0,NaN,NaN,END,info
2404,NaN,NaN,NaN,NaN,NaN

In [84]:
ai_task_clean = ai_task_clean[ai_task_clean['Response Type'] == 'response']
ai_task_clean = ai_task_clean.drop_duplicates(
    subset=["Participant Private ID", "Page", "Question"], 
    keep="last"
)

ai_task_columns = ['Participant Private ID','Page', 'Question', 'Response']
ai_task_clean = ai_task_clean[ai_task_columns]

ai_task_clean

,Participant Private ID,Page,Question,Response
151,12315511.0,Page 22,Predict the midpoint of the next candlestick,117
153,12315511.0,Page 22,How confident are you in your prediction (1-5),4
155,12315511.0,Page 22,Do you believe the analysis in the visualizati...,4
157,12315511.0,Page 22,How clear do you think the visualization is (1-5),4
158,12315511.0,Page 133,Predict the midpoint of the next candlestick,97
...,...,...,...,...
2395,12315870.0,Page 96,How clear do you think the visualization is (1-5),3
2396,12315870.0,Page 150,Predict the midpoint of the next candlestick,107
2398,12315870.0,Page 150,How confident are you in your prediction (1-5),3
2400,12315870.0,Page 150,Do you believe the analysis in the visualizati...,3
2402,12315870.0,Page 150,How clear do you think the visualization is (1-5),3

In [85]:
ai_task_clean.to_csv(f"{out_path}Clean_Task.csv")

## Clean task

In [86]:
clean = pd.read_csv(f"{in_path}{files[2]}")
clean.columns

Index(['Event Index', 'UTC Timestamp', 'UTC Date and Time', 'Local Timestamp',
       'Local Timezone', 'Local Date and Time', 'Experiment ID',
       'Experiment Version', 'Tree Node Key', 'Repeat Key', 'Schedule ID',
       'Participant Public ID', 'Participant Private ID',
       'Participant Starting Group', 'Participant Status',
       'Participant Completion Code', 'Participant External Session ID',
       'Participant Device Type', 'Participant Device', 'Participant OS',
       'Participant Browser', 'Participant Monitor Size',
       'Participant Viewport Size', 'Checkpoint', 'Room ID', 'Room Order',
       'Task Name', 'Task Version', 'Unnamed: 28', 'Page', 'Page ID',
       'Page Counter', 'Question', 'Response Type', 'Key', 'Response', 'Tag',
       'OptionOrder', 'Object Name', 'Object Number', 'Object ID',
       'Manipulation: '],
      dtype='object')

In [87]:
clean_columns = ['Participant Private ID','Page', 'Question', 'Response', 'Response Type']
clean_clean = clean[clean_columns]
clean_clean

,Participant Private ID,Page,Question,Response,Response Type
0,12315511.0,NaN,NaN,BEGIN,info
1,12315511.0,Page 31,NaN,100,info
2,12315511.0,Page 6,NaN,100,info
3,12315511.0,Page 16,NaN,100,info
4,12315511.0,Page 26,NaN,100,info
...,...,...,...,...,...
400,12315870.0,Page 11,Predict the midpoint of the next candlestick,108,response
401,12315870.0,Page 11,How confident are you in your prediction (1-5),3,response
402,12315870.0,Page 11,How confident are you in your prediction (1-5),3,response
403,12315870.0,NaN,NaN,END,info
404,NaN,NaN,NaN,NaN,NaN

In [88]:
clean_clean = clean_clean[clean_clean['Response Type'] == 'response']
clean_clean = clean_clean.drop_duplicates(
    subset=["Participant Private ID", "Page", "Question"], 
    keep="last"
)


clean_clean_columns = ['Participant Private ID','Page', 'Question', 'Response']
clean_clean = clean_clean[clean_clean_columns]

clean_clean

,Participant Private ID,Page,Question,Response
51,12315511.0,Page 31,Predict the midpoint of the next candlestick,106
53,12315511.0,Page 31,How confident are you in your prediction (1-5),4
54,12315511.0,Page 6,Predict the midpoint of the next candlestick,104
56,12315511.0,Page 6,How confident are you in your prediction (1-5),4
57,12315511.0,Page 16,Predict the midpoint of the next candlestick,102
...,...,...,...,...
396,12315870.0,Page 44,How confident are you in your prediction (1-5),3
397,12315870.0,Page 24,Predict the midpoint of the next candlestick,104
399,12315870.0,Page 24,How confident are you in your prediction (1-5),3
400,12315870.0,Page 11,Predict the midpoint of the next candlestick,108
402,12315870.0,Page 11,How confident are you in your prediction (1-5),3

In [89]:
clean_clean.to_csv(f"{out_path}Clean_Task.csv")